# Author: @mvxt

##########################
# Common Definitions
##########################
aliases:
  - &project_dir "~/circleci-se-challenge"
  - &bucket_name "s3://circleci-se-challenge"
  - &container_config
    docker:
      - image: circleci/node:10.15.1-browsers
    working_directory: *project_dir

##########################
# Orb Inclusions
##########################
orbs:
  aws-s3: circleci/aws-s3@1.0.8

##########################
# Workflow Definitions
##########################
workflows:
  version: 2.1
  build-deploy:
    jobs:
      - test
      - test_parallel:
          requires:
            - test
      - some_other_job:
          requires:
            - test
      - approve_deploy:
          type: approval
          requires:
            - test_parallel
            - some_other_job
          filters:
            branches:
              only: master
      - deploy:
          context: orpheus-prod
          requires:
            - approve_deploy
          filters:
            branches:
              only: master

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master

    jobs:
      - test_parallel

##########################
# Job Definitions
##########################
version: 2.1
jobs:
  test:
    <<: *container_config # See common definitions
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install deps
          command: yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Split TestCafe tests between containers and run them 
          command: |
            TESTFILES=$(ls test/*)
            echo "Testing $TESTFILES on this container"
            yarn runTests -- ${TESTFILES}
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
      - persist_to_workspace:
          root: .
          paths:
            - css
            - img
            - index.html
            - js
            - mail
            - scss
            - vendor

  test_parallel:
    <<: *container_config # See common definitions
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install deps
          command: yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Split TestCafe tests between containers and run them 
          command: |
            TESTFILES=$(circleci tests glob test/* | circleci tests split --total=4)
            echo "Testing $TESTFILES on this container"
            yarn runTests -- ${TESTFILES}
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
      - persist_to_workspace:
          root: .
          paths:
            - css
            - img
            - index.html
            - js
            - mail
            - scss

  some_other_job:
    <<: *container_config # See common definitions
    steps:
      - checkout
      - run:
          name: Echo a message
          command: echo "Hello World! Now you can deploy your app!"

  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: *project_dir
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: .
          to: *bucket_name

