# Author: @mvxt
aliases:
  - &project_dir "~/circleci-se-challenge"
  - &bucket_name "s3://circleci-se-challenge"

version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.3

jobs:
  test:
    docker:
      - image: circleci/node:10.15.1-browsers
    working_directory: *project_dir
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install deps
          command: yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Split TestCafe tests between containers and run them 
          command: |
            TESTFILES=$(circleci tests glob test/* | circleci tests split --total=2)
            echo "Testing $TESTFILES on this container"
            yarn runTests -- ${TESTFILES}
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: *project_dir
    steps:
      - checkout
      - aws-s3/copy:
          from: index.html
          to: *bucket_name

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - test
      - approve_deploy:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          context: orpheus-prod
          requires:
            - approve_deploy
          filters:
            branches:
              only: master

